apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wp.fullname" . }}
  labels:
    {{- include "wp.labels" . | nindent 4 }}
data:
  FAABLE_DATABASE_HOST: {{ .Values.database.host }}
  FAABLE_DATABASE_NAME: {{ .Values.database.prefix }}{{ .Release.Name }}
  FAABLE_DATABASE_USER: {{ .Values.database.user }}
  FAABLE_DATABASE_PASSWORD: {{ .Values.database.password }}
  