apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wp.fullname" . }}-data
  labels:
    {{- include "wp.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.persistence.storageClassName }}